name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Pull Request"]
    types:
      - completed

jobs:
  trunk_check:
    name: Trunk Check Annotate
    runs-on: ubuntu-latest

    steps:
      - name: Trunk Check
        uses: ./gh_action
        with:
          cache: false
          upload-annotations: true
